# Generated by Django 2.2.5 on 2019-09-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiProje', '0002_ozet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ozet',
            old_name='frekans',
            new_name='frequency',
        ),
    ]
